spring.application.name=notification
spring.profiles.active=prod
server.port=${NOTIFICATION_SERVER_PORT:8085}
spring.profiles.active=prod
# smtp
spring.mail.host=${SMTP_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:ef5dbdf3615bcb}
spring.mail.password=${SMTP_PASSWORD:9199de11023977}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.enable=${IS_EMAIL_ENABLED:true}
app.email.default-from=${DEFAULT_FROM_EMAIL:noreply@example.com}

# eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8081/eureka}
eureka.instance.preferIpAddress=true

# mq
mq.host=${SPRING_RABBITMQ_HOST:localhost}
mq.port=${SPRING_RABBITMQ_PORT:5672}
mq.username=${SPRING_RABBITMQ_USERNAME:guest}
mq.password=${SPRING_RABBITMQ_PASSWORD:guest}
mq.ssl=${RABBITMQ_SSL:false}
mq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}
# spring.rabbitmq.vhost=

# stomp relay (RabbitMQ STOMP plugin)
stomp.relay.host=${STOMP_RELAY_HOST:${mq.host}}
stomp.relay.port=${STOMP_RELAY_PORT:61613}
stomp.relay.username=${STOMP_RELAY_USERNAME:${mq.username}}
stomp.relay.password=${STOMP_RELAY_PASSWORD:${mq.password}}
stomp.relay.system-login=${STOMP_RELAY_SYSTEM_LOGIN:${mq.username}}
stomp.relay.system-passcode=${STOMP_RELAY_SYSTEM_PASSCODE:${mq.password}}

# service-specific
appdomain=${APP_BASE_URL:http://localhost:3000}

spring.threads.virtual.enabled=true

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info


# MQ Configuration
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=30000
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=15
spring.rabbitmq.listener.simple.prefetch=3
